version: '3'
services:
  selenoid:
    networks:
      selenoid: null
    image: aerokube/selenoid:latest-release
    container_name: "selenoid"
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      - selenoid
    links:
      - selenoid
    container_name: "selenoid-ui"
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  jenkins:
    image: "jenkins/jenkins:lts"
    ports:
      - "8880:8080"
      - "50000:50000"
    environment:
      JENKINS_OPTS: "--sessionTimeout=300"
    restart: "always"
    container_name: "jenkins"
    volumes:
      - "./jenkins_compose/jenkins_configuration:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - selenoid

networks:
  selenoid:
    external:
      name: selenoid # This assumes network is already created
