version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"

  jenkins:
    image: jenkins/jenkins:lts
    network_mode: bridge
    privileged: true
    user: root
    ports:
      - 8088:8088
      - 50000:50000
    container_name: jenkins
    environment:
      - JENKINS_OPTS="--httpPort=8088"
    volumes:
      - "./jenkins_compose/jenkins_configuration:/var/jenkins_home"
